version: 2.1

.service_name: &service_name github-discussions-crawler

.default_image: &default_image
  docker:
  - image: circleci/openjdk:8-jdk
  working_directory: ~/project

.defaults: &defaults
  environment:
    MAINTAINER: "info@qualiton.org"
    SERVICE_NAME: *service_name
    HELM_VERSION: "v2.10.0"

.attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/

.persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: ~/
    paths:
    - project/*

.cache_key: &cache_key
              v1-repo-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Branch }}-{{ checksum "project/Dependencies.scala"}}

.restore_cache: &restore_cache
  restore_cache:
    name: Restoring project cache
    keys:
    - *cache_key

jobs:
  compile:
    <<: *default_image
    steps:
    - checkout
    - *restore_cache
    - run:
        name: Compile project
        command: sbt ";clean ;compile ;test:compile ;it:compile ;e2e:compile"
    - save_cache:
        name: Saving project cache
        key: *cache_key
        paths:
        - ~/.m2
        - ~/.ivy2
        - ~/.sbt
        - target/resolution-cache
        - project/target/resolution-cache
    - *persist_to_workspace

  test:
    <<: *default_image
    steps:
    - *attach_workspace
    - *restore_cache
    - run:
        name: Run tests
        command: sbt test

  ittest:
    <<: *default_image
    steps:
    - *attach_workspace
    - *restore_cache
    - run:
        name: Run integration tests
        command: sbt it:test

  e2etest:
    <<: *default_image
    steps:
    - *attach_workspace
    - *restore_cache
    - run:
        name: Run e2e tests
        command: sbt e2e:test

  build:
    <<: *default_image
    <<: *defaults
    steps:
    - *attach_workspace
    - *restore_cache
    - setup_remote_docker
    - run:
        name: Setup git
        command: |
          sudo ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts && \
          git config --global user.name "lachatak" && \
          git config --global user.email "krisztian.lachata@gmail.com"
    - run:
        name: Sbt release
        command: |
          sbt "release with-defaults"
    - run:
        name: Docker Login
        command: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - run:
        name: Push container to registry
        command: |
          docker push "$DOCKER_USERNAME/$SERVICE_NAME"
    - *persist_to_workspace

  release_chart:
    <<: *default_image
    <<: *defaults
    steps:
    - *attach_workspace
    - run:
        name: Release chart
        command: |
          curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash -s -- -v $HELM_VERSION
          helm init --client-only
          cd .helm
          helm package $SERVICE_NAME
          mv $SERVICE_NAME-*.tgz /tmp
          git checkout .
          git checkout gh-pages
          pwd
          git clean -f -d
          pwd
          git branch --track gh-pages origin/gh-pages
          pwd
          mv /tmp/$SERVICE_NAME-*.tgz .
          helm repo index . --url https://qualiton.github.io/github-discussions-crawler/
          VERSION=`echo "github-discussions-crawler-0.0.1-SNAPSHOT.tgz" | awk -F"github-discussions-crawler-" '{print $2}' | awk -F".tgz" '{print $1}'`
          git commit -a -m "change index for $VERSION"
          git push origin gh-pages

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - compile
    #    - test:
    #        requires:
    #        - compile
    #    - ittest:
    #        requires:
    #        - compile
    #    - e2etest:
    #        requires:
    #        - compile
    #    - build:
    #        filters:
    #          branches:
    #            only: master
    #        requires:
    #        - test
    #        - ittest
    #        - e2etest
    - release_chart:
        requires:
        - compile
