kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "fullname" . }}-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
