kind: Secret
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: github
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.AppVersion }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
data:
  api-token: {{ .Values.github.api_token | b64enc }}

---

kind: Secret
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: slack
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.AppVersion }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
data:
  api-token: {{ .Values.slack.api_token | b64enc }}

---

kind: Secret
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: database
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.AppVersion }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
data:
  jdbc-url: {{ .Values.database.jdbc_url | b64enc }}
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}
