kind: Secret
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: slack
data:
  token: {{ .Values.slack.token | b64enc }}

---

kind: Secret
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: github
data:
  token: {{ .Values.github.token | b64enc }}

---

kind: Secret
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: database
data:
  user: {{ .Values.database.user | b64enc }}
  password: {{ .Values.database.password | b64enc }}
  connection-url: {{ .Values.database.connection-url | b64enc }}
